import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import { api } from "../api";

interface Props {
  fileId: string;
  onClose: () => void;
}

export default function SummaryModal({ fileId, onClose }: Props) {
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api
      .summarize(fileId)
      .then((r) => setSummary(r.summary))
      .catch((e: Error) => setError(e.message || "Failed to generate summary. Please try again."))
      .finally(() => setLoading(false));
  }, [fileId]);

  // Close on backdrop click
  function handleBackdropClick(e: React.MouseEvent) {
    if (e.target === e.currentTarget) onClose();
  }

  return (
    <div
      className="fixed inset-0 flex items-center justify-center z-50 p-4"
      style={{ background: "rgba(15,23,42,0.7)" }}
      onClick={handleBackdropClick}
    >
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[85vh] flex flex-col overflow-hidden">
        {/* Gold accent bar */}
        <div className="h-1 w-full flex-shrink-0" style={{ background: "linear-gradient(90deg, #f59e0b, #fcd34d, #f59e0b)" }} />

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b flex-shrink-0" style={{ borderColor: "#f1f5f9" }}>
          <div className="flex items-center gap-2">
            <span style={{ color: "#f59e0b" }}>✦</span>
            <h2 className="text-base font-semibold" style={{ color: "#0f172a" }}>AI Paper Summary</h2>
            <span className="text-xs px-2 py-0.5 rounded-full" style={{ background: "rgba(15,23,42,0.07)", color: "#64748b" }}>
              Photon Academy
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg transition-colors"
            style={{ color: "#94a3b8" }}
            onMouseEnter={(e) => (e.currentTarget.style.background = "#f1f5f9")}
            onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
            aria-label="Close"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {loading && (
            <div className="flex flex-col items-center justify-center py-16 gap-4">
              <div className="w-10 h-10 rounded-full animate-spin" style={{ border: "3px solid #f59e0b", borderTopColor: "transparent" }} />
              <p className="text-sm" style={{ color: "#64748b" }}>Analysing paper with Claude AI…</p>
              <p className="text-xs" style={{ color: "#94a3b8" }}>This usually takes 10–20 seconds</p>
            </div>
          )}

          {error && (
            <div className="rounded-lg p-4 text-sm" style={{ background: "#fef2f2", border: "1px solid #fecaca", color: "#dc2626" }}>
              {error}
            </div>
          )}

          {summary && (
            <div className="prose prose-sm max-w-none prose-headings:text-slate-800 prose-strong:text-slate-900">
              <ReactMarkdown>{summary}</ReactMarkdown>
            </div>
          )}
        </div>

        {/* Footer */}
        {!loading && (
          <div className="px-6 py-3 border-t flex-shrink-0" style={{ borderColor: "#f1f5f9", background: "#f8fafc" }}>
            <p className="text-xs" style={{ color: "#94a3b8" }}>
              Summary generated by Claude AI — always verify against the official markscheme.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
